<!doctype html>
<html lang="pl">
<head>
	<meta charset="utf-8">
	<title>The HTML5 Herald</title>
	<meta name="description" content="The HTML5 Herald">
	<meta name="author" content="SitePoint">
	<base href="<?php echo BASE_URL ?>">
	<link rel="stylesheet" href="<?php echo BASE_URL ?>Vendor\bootstrap-4.1.3-dist\css\bootstrap.css">
	<link rel="stylesheet" href="<?php echo BASE_URL ?>View\Css\style.css">
	<script src="<?php echo BASE_URL ?>View\Js\jquery-3.2.1.slim.min.js"></script>
	<script src="<?php echo BASE_URL ?>View\Js\popper.min.js"></script>
    <script src="<?php echo BASE_URL ?>Vendor\bootstrap-4.1.3-dist\js\bootstrap.js"></script>
</head>
<body>
