version: '3.1'

services:

  db:
    image: mariadb:10.5.9
    volumes:
      - db:/var/lib/mysql
    ports:
      - "6603:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: 'no'

  php:
    build:
      context: .docker
      dockerfile: Dockerfile-php
    restart: 'no'
    volumes:
      - ./html:/var/www/html
      - ./.config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: 'no'

  ws:
    image: debian:buster
    depends_on:
      - db
      - php
    build:
      context: .docker
      dockerfile: Dockerfile-ws
    volumes:
      - ./html:/var/www/html
      - ./.config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
    restart: 'no'

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    restart: 'no'
    
volumes:
  db: